#!/usr/bin/env node

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { basename, dirname, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

/** Workspaces whose tsconfig.json compiles .mts sources to the .mjs and .d.mts beside them. */
export const TYPESCRIPT_PROJECTS = Object.freeze(['packages/artifact', 'packages/design']);

// This readable input compiles before the skills, HTML shells and exported editor styles read it.
// Keep the public CSS path stable; installed DOM parsers and older browsers require flat rules.
export const STYLESHEET_SOURCE_OUTPUTS = Object.freeze({
  'packages/artifact/lib/artifact/ui/studio-shell.source.css':
    'packages/artifact/lib/artifact/ui/studio-shell.css',
});

// Declaration paths resolve under this directory and map back beside their sources; nothing
// is written there. An in-place emit would collide with the JavaScript modules allowJs reads.
const EMIT_DIRECTORY = '.typescript-emit';

export const TYPESCRIPT_OUTPUT_BANNER =
  '// generated by scripts/typescript/compile-sources.mjs from';

export class TypeScriptSourceError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = 'TypeScriptSourceError';
    this.code = code;
    this.details = details;
  }
}

const posix = (path) => path.split(sep).join('/');

function formatDiagnostics(diagnostics, root) {
  return ts.formatDiagnostics(diagnostics, {
    getCanonicalFileName: (fileName) => fileName,
    getCurrentDirectory: () => root,
    getNewLine: () => '\n',
  });
}

function readProject(root, project) {
  const projectRoot = resolve(root, project);
  const configDiagnostics = [];
  const parsed = ts.getParsedCommandLineOfConfigFile(
    resolve(projectRoot, 'tsconfig.json'),
    {
      noEmit: false,
      declaration: true,
      emitDeclarationOnly: true,
      rootDir: projectRoot,
      outDir: resolve(projectRoot, EMIT_DIRECTORY),
    },
    {
      ...ts.sys,
      onUnRecoverableConfigFileDiagnostic: (diagnostic) => configDiagnostics.push(diagnostic),
    },
  );
  const diagnostics = [...configDiagnostics, ...(parsed?.errors ?? [])];
  if (!parsed || diagnostics.length > 0) {
    throw new TypeScriptSourceError(
      'E_TYPESCRIPT_CONFIG',
      `Reading ${project}/tsconfig.json failed:\n${formatDiagnostics(diagnostics, root)}`,
      { project, count: diagnostics.length },
    );
  }
  return { projectRoot, parsed };
}

/**
 * Strip types with the project's own esbuild, the version that bundles its browser runtimes.
 * esbuild keeps the source's line layout, so a bundle built from this output matches one
 * built from the equivalent hand-written JavaScript; tsc's printer would reflow it.
 */
function rewriteTsxImports(text, source) {
  return text.replace(/(['"])(\.{1,2}\/[^'"]+)\.js\1/gu, (match, quote, path) =>
    existsSync(resolve(dirname(source.fileName), `${path}.tsx`))
      ? `${quote}${path}.mjs${quote}`
      : match,
  );
}

function emitJavaScript(projectRoot, source) {
  const { transformSync } = createRequire(resolve(projectRoot, 'package.json'))('esbuild');
  return rewriteTsxImports(
    transformSync(source.text, {
      sourcefile: source.fileName,
      loader: source.fileName.endsWith('.tsx') ? 'tsx' : 'ts',
      jsx: 'automatic',
      format: 'esm',
      target: 'es2022',
      charset: 'utf8',
      legalComments: 'inline',
      tsconfigRaw: { compilerOptions: { verbatimModuleSyntax: true } },
    }).code,
    source,
  );
}

function compileProject(root, project) {
  const { projectRoot, parsed } = readProject(root, project);
  const program = ts.createProgram({ rootNames: parsed.fileNames, options: parsed.options });
  const sources = parsed.fileNames.map((fileName) => program.getSourceFile(fileName));
  const diagnostics = [...program.getOptionsDiagnostics(), ...program.getGlobalDiagnostics()];
  for (const source of sources) {
    diagnostics.push(
      ...program.getSyntacticDiagnostics(source),
      ...program.getSemanticDiagnostics(source),
      ...program.getDeclarationDiagnostics(source),
    );
  }
  if (diagnostics.length > 0) {
    throw new TypeScriptSourceError(
      'E_TYPESCRIPT_DIAGNOSTICS',
      `${project} has ${diagnostics.length} TypeScript error${diagnostics.length === 1 ? '' : 's'}:\n${formatDiagnostics(diagnostics, root)}`,
      { project, count: diagnostics.length },
    );
  }
  const emitRoot = resolve(projectRoot, EMIT_DIRECTORY);
  const outputs = {};
  for (const source of sources) {
    const banner = `${TYPESCRIPT_OUTPUT_BANNER} ${basename(source.fileName)}\n`;
    const target = posix(relative(root, source.fileName)).replace(/\.(?:mts|tsx)$/u, '');
    outputs[`${target}.mjs`] = `${banner}${emitJavaScript(projectRoot, source)}`;
    const result = program.emit(source, (fileName, text) => {
      if (
        resolve(projectRoot, relative(emitRoot, fileName)).replace(/\.d\.ts$/u, '.d.mts') !==
        resolve(root, `${target}.d.mts`)
      )
        throw new TypeScriptSourceError(
          'E_TYPESCRIPT_EMIT',
          `Unexpected declaration output ${fileName} for ${target}.mts.`,
          { source: `${target}.mts` },
        );
      outputs[`${target}.d.mts`] = `${banner}${rewriteTsxImports(text, source)}`;
    });
    if (result.emitSkipped || !outputs[`${target}.d.mts`]) {
      throw new TypeScriptSourceError(
        'E_TYPESCRIPT_EMIT',
        `TypeScript emitted no declaration for ${target}.mts.`,
        { source: `${target}.mts` },
      );
    }
  }
  return outputs;
}

/** Type-check every project and return each emitted .mjs and .d.mts by repository path. */
export function renderTypeScriptOutputs({ root = repositoryRoot } = {}) {
  const outputs = Object.assign(
    {},
    ...TYPESCRIPT_PROJECTS.map((project) => compileProject(root, project)),
  );
  return Object.fromEntries(
    Object.entries(outputs).sort(([left], [right]) => left.localeCompare(right)),
  );
}

/** Lower owned CSS nesting at build time using the same installed esbuild as the browser UI. */
export function renderStylesheetOutputs({ root = repositoryRoot } = {}) {
  const { transformSync } = createRequire(resolve(root, 'packages/artifact/package.json'))(
    'esbuild',
  );
  const outputs = {};
  for (const [source, target] of Object.entries(STYLESHEET_SOURCE_OUTPUTS)) {
    const result = transformSync(readFileSync(resolve(root, source), 'utf8'), {
      sourcefile: source,
      loader: 'css',
      supported: { nesting: false },
      minifyWhitespace: true,
      charset: 'utf8',
      legalComments: 'inline',
      logLevel: 'silent',
    });
    if (result.warnings.length) {
      throw new TypeScriptSourceError(
        'E_STYLESHEET_WARNINGS',
        `Compiling ${source} produced warnings:\n${result.warnings.map(({ text }) => text).join('\n')}`,
        { source, count: result.warnings.length },
      );
    }
    outputs[target] =
      `/* generated by scripts/typescript/compile-sources.mjs from ${basename(source)} */\n` +
      result.code;
  }
  return outputs;
}

export function staleTypeScriptTargets({ root = repositoryRoot, outputs } = {}) {
  const expected = outputs ?? renderTypeScriptOutputs({ root });
  return Object.entries(expected)
    .filter(([target, bytes]) => {
      const path = resolve(root, target);
      return !existsSync(path) || readFileSync(path, 'utf8') !== bytes;
    })
    .map(([target]) => target);
}

export function writeTypeScriptOutputs({ root = repositoryRoot, outputs } = {}) {
  const expected = outputs ?? renderTypeScriptOutputs({ root });
  const written = staleTypeScriptTargets({ root, outputs: expected });
  for (const target of written) writeFileSync(resolve(root, target), expected[target], 'utf8');
  return written;
}

function parseArgs(argv) {
  const unsupported = argv.filter((arg) => arg !== '--check');
  if (unsupported.length > 0) {
    throw new TypeScriptSourceError(
      'E_TYPESCRIPT_ARGUMENT',
      `Unsupported argument${unsupported.length === 1 ? '' : 's'}: ${unsupported.join(', ')}`,
      { unsupported },
    );
  }
  return { check: argv.includes('--check') };
}

export function runTypeScriptCompiler({
  argv = process.argv.slice(2),
  root = repositoryRoot,
} = {}) {
  const { check } = parseArgs(argv);
  const outputs = { ...renderTypeScriptOutputs({ root }), ...renderStylesheetOutputs({ root }) };
  if (check) {
    const stale = staleTypeScriptTargets({ root, outputs });
    if (stale.length > 0) {
      throw new TypeScriptSourceError(
        'E_TYPESCRIPT_DRIFT',
        `Compiled source outputs are stale:\n${stale.map((target) => `  - ${target}`).join('\n')}\nRun: npm run generate`,
        { staleTargets: stale },
      );
    }
    return { ok: true, mode: 'check', outputs: Object.keys(outputs).length };
  }
  return { ok: true, mode: 'write', written: writeTypeScriptOutputs({ root, outputs }) };
}

function main() {
  try {
    const result = runTypeScriptCompiler();
    if (result.mode === 'check') {
      process.stdout.write(`Compiled source outputs are current (${result.outputs} files).\n`);
    } else if (result.written.length === 0) {
      process.stdout.write('Compiled source outputs already current.\n');
    } else {
      process.stdout.write(
        `Compiled source outputs:\n${result.written.map((target) => `  - ${target}`).join('\n')}\n`,
      );
    }
  } catch (error) {
    process.stderr.write(`${error?.code ?? 'E_TYPESCRIPT'}: ${error.message}\n`);
    process.exitCode = 1;
  }
}

if (resolve(process.argv[1] ?? '') === fileURLToPath(import.meta.url)) main();
