/**
 * Stakeholder report generation from context packs and Handlebars templates.
 */

import path from 'node:path';
import type {
  OpenPlanrConfig,
  StakeholderReportContext,
  StakeholderReportFormat,
  StakeholderReportType,
} from '../models/types.js';
import { ensureDir, writeFile } from '../utils/fs.js';
import { logger } from '../utils/logger.js';
import { type BuildContextOptions, buildStakeholderReportContext } from './context-pack-service.js';
import { renderTemplate } from './template-service.js';

const TEMPLATE_BY_TYPE: Record<StakeholderReportType, string> = {
  sprint: 'reports/sprint.md.hbs',
  weekly: 'reports/weekly.md.hbs',
  executive: 'reports/executive.md.hbs',
  standup: 'reports/standup.md.hbs',
  retro: 'reports/retrospective.md.hbs',
  release: 'reports/release-notes.md.hbs',
};

export function resolveReportTemplate(reportType: StakeholderReportType): string {
  return TEMPLATE_BY_TYPE[reportType];
}

export async function generateStakeholderReportMarkdown(
  context: StakeholderReportContext,
  config: OpenPlanrConfig,
): Promise<string> {
  const templatePath = resolveReportTemplate(context.reportType);
  try {
    return await renderTemplate(
      templatePath,
      { ...context, json: JSON.stringify(context, null, 2) },
      config.templateOverrides,
    );
  } catch (err) {
    logger.debug('report template render failed', err);
    throw new Error(
      `Failed to render report template "${templatePath}": ${(err as Error).message}`,
    );
  }
}

function wrapHtmlDocument(title: string, bodyMarkdownAsHtml: string, accent?: string): string {
  const color = accent || '#4169E1';
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 52rem; margin: 2rem auto; padding: 0 1rem; color: #111; }
    h1 { border-bottom: 2px solid ${color}; padding-bottom: 0.25rem; }
    h2 { margin-top: 1.75rem; color: #222; }
    code, pre { background: #f4f4f4; padding: 0.2em 0.4em; border-radius: 4px; }
    a { color: ${color}; }
    .meta { color: #555; font-size: 0.9rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <p class="meta">Generated by OpenPlanr</p>
  <div class="content">
${bodyMarkdownAsHtml}
  </div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Minimal markdown → HTML for reports (headings, lists, links, paragraphs). */
export function markdownToBasicHtml(md: string): string {
  const lines = md.split(/\r?\n/);
  const out: string[] = [];
  let inUl = false;
  const flushUl = () => {
    if (inUl) {
      out.push('</ul>');
      inUl = false;
    }
  };
  for (const line of lines) {
    const h2 = line.match(/^## (.+)$/);
    if (h2) {
      flushUl();
      out.push(`<h2>${escapeHtml(h2[1])}</h2>`);
      continue;
    }
    const h1 = line.match(/^# (.+)$/);
    if (h1) {
      flushUl();
      out.push(`<h1>${escapeHtml(h1[1])}</h1>`);
      continue;
    }
    const li = line.match(/^\s*[-*]\s+(.+)$/);
    if (li) {
      if (!inUl) {
        out.push('<ul>');
        inUl = true;
      }
      out.push(`<li>${inlineMd(li[1])}</li>`);
      continue;
    }
    if (line.trim() === '') {
      flushUl();
      continue;
    }
    flushUl();
    out.push(`<p>${inlineMd(line)}</p>`);
  }
  flushUl();
  return out.join('\n');
}

function inlineMd(text: string): string {
  let s = escapeHtml(text);
  s = s.replace(/`([^`]+)`/g, '<code>$1</code>');
  s = s.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  return s;
}

export async function formatStakeholderReportOutput(
  context: StakeholderReportContext,
  config: OpenPlanrConfig,
  format: StakeholderReportFormat,
): Promise<{ markdown: string; html?: string }> {
  const markdown = await generateStakeholderReportMarkdown(context, config);
  if (format === 'html') {
    const inner = markdownToBasicHtml(markdown);
    const title = `${context.projectName} — ${context.reportType} report`;
    const html = wrapHtmlDocument(title, inner, context.branding?.accentColor);
    return { markdown, html };
  }
  return { markdown };
}

export async function generateStakeholderReport(
  projectDir: string,
  config: OpenPlanrConfig,
  opts: BuildContextOptions & { format: StakeholderReportFormat },
): Promise<{ markdown: string; html?: string; context: StakeholderReportContext }> {
  const context = await buildStakeholderReportContext(projectDir, config, opts);
  const { markdown, html } = await formatStakeholderReportOutput(context, config, opts.format);
  return { markdown, html, context };
}

export async function writeReportOutputs(args: {
  projectDir: string;
  config: OpenPlanrConfig;
  baseName: string;
  markdown: string;
  html?: string;
  outputDir?: string;
}): Promise<{ mdPath?: string; htmlPath?: string }> {
  const rel = args.outputDir ?? path.join(args.config.outputPaths.agile, 'reports');
  const dir = path.join(args.projectDir, rel);
  await ensureDir(dir);
  const stamp = new Date().toISOString().split('T')[0];
  const safe = args.baseName.replace(/[^a-z0-9-_]+/gi, '-').toLowerCase();
  const mdPath = path.join(dir, `${stamp}-${safe}.md`);
  await writeFile(mdPath, args.markdown);
  let htmlPath: string | undefined;
  if (args.html) {
    htmlPath = path.join(dir, `${stamp}-${safe}.html`);
    await writeFile(htmlPath, args.html);
  }
  return { mdPath, htmlPath };
}
