import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { canonicalDigest, canonicalize, sha256Digest } from './canonical.js';
import {
  applyJournalTransaction,
  type JournalWrite,
  prepareJournalTransaction,
} from './journal.js';
import {
  OPERATING_BOARD_ROLES,
  renderOperatingBoardReport,
  renderOperatingBrief,
  renderOperatingEvidenceIndex,
  selectCycleState,
} from './projection.js';
import { assertOperatingArtifact } from './protocol.js';
import { operatingStalledItems } from './stalled-item-service.js';
import { OperateError, type OperatingEventHead, type OperatingState } from './types.js';

const OPERATE_ROOT = '.planr/operate';
const PROJECTION_ROOT = `${OPERATE_ROOT}/projections`;
const STATE_PATH = `${PROJECTION_ROOT}/state.json`;
const EVIDENCE_INDEX_PATH = `${OPERATE_ROOT}/evidence-index.json`;
const MARKDOWN_PROJECTIONS = [
  {
    relativePath: `${PROJECTION_ROOT}/register.md`,
    markerName: 'operate-findings-register',
    render: renderFindingRegister,
  },
  {
    relativePath: `${PROJECTION_ROOT}/decisions.md`,
    markerName: 'operate-decisions-register',
    render: renderDecisionRegister,
  },
  {
    relativePath: `${PROJECTION_ROOT}/data-gaps.md`,
    markerName: 'operate-data-gaps-register',
    render: renderDataGapRegister,
  },
  {
    relativePath: `${PROJECTION_ROOT}/backlog.md`,
    markerName: 'operate-backlog-register',
    render: renderBacklogRegister,
  },
] as const;
// FR5 readable tree: one consolidated Markdown file per register rendered at the
// top level (the workspace path getters T-001 added), above the `.state/`
// internals. `findings.md`/`decisions.md`/`gaps.md` reuse the register renderers
// so the readable tree and the projections directory stay byte-consistent.
const READABLE_TREE_PROJECTIONS = [
  {
    relativePath: `${OPERATE_ROOT}/brief.md`,
    markerName: 'operate-brief',
    render: renderOperatingBrief,
  },
  {
    relativePath: `${OPERATE_ROOT}/findings.md`,
    markerName: 'operate-findings-register',
    render: renderFindingRegister,
  },
  {
    relativePath: `${OPERATE_ROOT}/decisions.md`,
    markerName: 'operate-decisions-register',
    render: renderDecisionRegister,
  },
  {
    relativePath: `${OPERATE_ROOT}/gaps.md`,
    markerName: 'operate-data-gaps-register',
    render: renderDataGapRegister,
  },
  {
    relativePath: `${OPERATE_ROOT}/routes.md`,
    markerName: 'operate-routes-register',
    render: renderRouteRegister,
  },
] as const;
const CYCLE_BRIEF_MARKER = 'operate-cycle-brief';
const BOARD_MARKER = 'operate-board';

export type OperatingProjectionDriftStatus = 'absent' | 'current' | 'drift';

export interface OperatingProjectionDrift {
  path: string;
  status: OperatingProjectionDriftStatus;
  expectedDigest: `sha256:${string}`;
  actualDigest: `sha256:${string}` | null;
  reason?: string;
}

export interface OperatingProjectionFile {
  relativePath: string;
  content: string;
  markerName?: string;
  managedContent?: string;
}

export interface OperatingProjectionPreview {
  stateDigest: `sha256:${string}`;
  eventHead: OperatingEventHead;
  previewDigest: `sha256:${string}`;
  files: OperatingProjectionFile[];
  changedPaths: string[];
  drift: OperatingProjectionDrift[];
}

export interface PersistOperatingProjectionResult extends OperatingProjectionPreview {
  transactionId: string | null;
}

function value(record: Record<string, unknown>, key: string, fallback = ''): string {
  const candidate = record[key];
  if (typeof candidate === 'string' && candidate.trim()) {
    return candidate.replace(/\s+/g, ' ').trim();
  }
  if (typeof candidate === 'number' || typeof candidate === 'boolean') {
    return String(candidate);
  }
  return fallback;
}

function markdownCell(candidate: unknown, fallback = '—'): string {
  const rendered =
    typeof candidate === 'string' || typeof candidate === 'number' || typeof candidate === 'boolean'
      ? String(candidate)
      : fallback;
  const withoutControls = [...rendered]
    .filter((character) => {
      const codePoint = character.codePointAt(0) ?? 0;
      return (
        codePoint === 9 ||
        codePoint === 10 ||
        codePoint === 13 ||
        (codePoint >= 32 && codePoint !== 127)
      );
    })
    .join('');
  const normalized = withoutControls.replace(/\s+/g, ' ').trim();
  return (normalized || fallback).replaceAll('\\', '\\\\').replaceAll('|', '\\|');
}

function evidenceRefs(record: Record<string, unknown>): string {
  if (!Array.isArray(record.evidenceRefs)) return '—';
  const refs = [
    ...new Set(record.evidenceRefs.filter((entry): entry is string => typeof entry === 'string')),
  ].sort();
  return refs.length > 0 ? refs.map((entry) => `\`${markdownCell(entry)}\``).join(', ') : '—';
}

function generatedHeader(state: OperatingState, title: string): string[] {
  return [
    `# ${title}`,
    '',
    '> Generated by `planr operate` from canonical events. Edit operating state through the CLI.',
    `> Event head: ${state.eventHead.sequence} / ${state.eventHead.hash ?? 'genesis'}`,
    `> Projection time: ${state.generatedAt}`,
    '',
  ];
}

function renderFindingRegister(state: OperatingState): string {
  const findings = [...state.findings].sort((left, right) => left.id.localeCompare(right.id));
  const stalledById = new Map(
    operatingStalledItems(state).map((item) => [item.id, item.stalledCycles]),
  );
  return [
    ...generatedHeader(state, 'Operating Findings Register'),
    '| Finding | Status | Lane | Owner | Severity | Score | Stalled cycles | Title | Evidence |',
    '|---|---|---|---|---|---:|---:|---|---|',
    ...(findings.length > 0
      ? findings.map(
          (finding) =>
            `| ${markdownCell(finding.id)} | ${markdownCell(finding.status)} | ${markdownCell(
              finding.lane,
            )} | ${markdownCell(finding.owner)} | ${markdownCell(
              finding.severity,
            )} | ${markdownCell(finding.score, '0')} | ${markdownCell(
              stalledById.get(finding.id) ?? 0,
              '0',
            )} | ${markdownCell(finding.title)} | ${evidenceRefs(finding)} |`,
        )
      : ['| — | — | — | — | — | 0 | 0 | No findings recorded. | — |']),
  ].join('\n');
}

function renderDecisionRegister(state: OperatingState): string {
  const stalledById = new Map(
    operatingStalledItems(state).map((item) => [item.id, item.stalledCycles]),
  );
  const decisions = [...state.decisions].sort((left, right) => {
    const deadlineDelta = value(left, 'deadline').localeCompare(value(right, 'deadline'));
    return deadlineDelta || left.id.localeCompare(right.id);
  });
  return [
    ...generatedHeader(state, 'Operating Decisions'),
    '| Decision | Status | Owner | Deadline | Stalled cycles | Reversibility | Question | Recommendation |',
    '|---|---|---|---|---:|---|---|---|',
    ...(decisions.length > 0
      ? decisions.map(
          (decision) =>
            `| ${markdownCell(decision.id)} | ${markdownCell(
              decision.status,
            )} | ${markdownCell(decision.owner)} | ${markdownCell(
              decision.deadline,
            )} | ${markdownCell(stalledById.get(decision.id) ?? 0, '0')} | ${markdownCell(
              decision.reversibility,
            )} | ${markdownCell(decision.question)} | ${markdownCell(decision.recommendation)} |`,
        )
      : ['| — | — | — | — | 0 | — | No decisions recorded. | — |']),
  ].join('\n');
}

function renderDataGapRegister(state: OperatingState): string {
  const gaps = [...state.dataGaps].sort((left, right) => left.id.localeCompare(right.id));
  return [
    ...generatedHeader(state, 'Operating Data Gaps'),
    '| Gap | Status | Owner | Question | Reason | Unblocks |',
    '|---|---|---|---|---|---|',
    ...(gaps.length > 0
      ? gaps.map((gap) => {
          const unblocks = Array.isArray(gap.unblocks)
            ? gap.unblocks
                .filter((entry): entry is string => typeof entry === 'string')
                .sort()
                .join(', ')
            : '';
          return `| ${markdownCell(gap.id)} | ${markdownCell(
            gap.status,
          )} | ${markdownCell(gap.owner)} | ${markdownCell(
            gap.question,
          )} | ${markdownCell(gap.reason)} | ${markdownCell(unblocks)} |`;
        })
      : ['| — | — | — | No data gaps recorded. | — | — |']),
  ].join('\n');
}

function renderBacklogRegister(state: OperatingState): string {
  const parked = state.findings
    .filter((finding) => finding.parked === true)
    .sort((left, right) => {
      const scoreDelta = Number(right.score ?? 0) - Number(left.score ?? 0);
      return scoreDelta || left.id.localeCompare(right.id);
    });
  return [
    ...generatedHeader(state, 'Operating Backlog'),
    '| Finding | Status | Owner | Score | Title | Parked reason | Evidence |',
    '|---|---|---|---:|---|---|---|',
    ...(parked.length > 0
      ? parked.map(
          (finding) =>
            `| ${markdownCell(finding.id)} | ${markdownCell(
              finding.status,
            )} | ${markdownCell(finding.owner)} | ${markdownCell(
              finding.score,
              '0',
            )} | ${markdownCell(finding.title)} | ${markdownCell(
              finding.problem ?? finding.proposal,
              'Deprioritized by the current attention cap.',
            )} | ${evidenceRefs(finding)} |`,
        )
      : ['| — | — | — | 0 | No parked findings. | — | — |']),
  ].join('\n');
}

function renderRouteRegister(state: OperatingState): string {
  const routes = [...state.routes].sort((left, right) => left.id.localeCompare(right.id));
  return [
    ...generatedHeader(state, 'Operating Routes'),
    '| Route | Cycle | State | Findings | Actions | Route digest |',
    '|---|---|---|---|---:|---|',
    ...(routes.length > 0
      ? routes.map((route) => {
          const actions = Array.isArray(route.actions)
            ? (route.actions as Array<{ findingId?: unknown }>)
            : [];
          const findingIds = Array.isArray(route.findingIds)
            ? route.findingIds.filter((entry): entry is string => typeof entry === 'string')
            : [
                ...new Set(
                  actions
                    .map((action) => action.findingId)
                    .filter((entry): entry is string => typeof entry === 'string'),
                ),
              ];
          const actionCount =
            typeof route.actionCount === 'number' ? route.actionCount : actions.length;
          return `| ${markdownCell(route.id)} | ${markdownCell(route.cycleId)} | ${markdownCell(
            route.state,
          )} | ${markdownCell(findingIds.sort().join(', '))} | ${markdownCell(
            actionCount,
            '0',
          )} | ${markdownCell(route.routeDigest)} |`;
        })
      : ['| — | — | — | — | 0 | No routes recorded. |']),
  ].join('\n');
}

function renderCycleBrief(state: OperatingState, cycleId: string): string {
  const selected = selectCycleState(state, cycleId);
  const brief = renderOperatingBrief(selected);
  const words = brief.split(/\s+/).filter(Boolean);
  if (words.length > 900) {
    throw new OperateError(
      'E_OPERATE_PROJECTION_DRIFT',
      `Cycle brief ${cycleId} exceeds the 900-word projection limit.`,
      { cycleId, words: words.length },
    );
  }
  return brief;
}

function markerExpression(markerName: string, edge: 'begin' | 'end'): RegExp {
  const escaped = markerName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return edge === 'begin'
    ? new RegExp(`^<!--\\s*##planr-${escaped}:begin##[^>]*-->[\\t ]*(?:\\r?\\n|$)`, 'gm')
    : new RegExp(`^<!--\\s*##planr-${escaped}:end##\\s*-->[\\t ]*`, 'gm');
}

function managedSection(
  content: string,
  markerName: string,
): { content: string; malformed: boolean } | null {
  const beginMatches = [...content.matchAll(markerExpression(markerName, 'begin'))];
  const endMatches = [...content.matchAll(markerExpression(markerName, 'end'))];
  if (beginMatches.length === 0 && endMatches.length === 0) return null;
  if (beginMatches.length !== 1 || endMatches.length !== 1) {
    return { content: '', malformed: true };
  }
  const begin = beginMatches[0];
  const end = endMatches[0];
  const beginEnd = (begin.index ?? 0) + begin[0].length;
  const endStart = end.index ?? 0;
  if (endStart < beginEnd) return { content: '', malformed: true };
  return {
    content: content.slice(beginEnd, endStart).trimEnd(),
    malformed: false,
  };
}

function beginMarker(markerName: string): string {
  return `<!-- ##planr-${markerName}:begin## (managed by planr CLI; preserve hand-edits outside this block) -->`;
}

function endMarker(markerName: string): string {
  return `<!-- ##planr-${markerName}:end## -->`;
}

function spliceProjectionBlock(
  existing: string,
  markerName: string,
  managedContent: string,
): string {
  const beginMatches = [...existing.matchAll(markerExpression(markerName, 'begin'))];
  const endMatches = [...existing.matchAll(markerExpression(markerName, 'end'))];
  const block = [beginMarker(markerName), managedContent.trimEnd(), endMarker(markerName)].join(
    '\n',
  );
  if (beginMatches.length === 0 && endMatches.length === 0) {
    if (existing.length === 0) return `${block}\n`;
    const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
    return `${existing}${separator}${block}\n`;
  }
  if (beginMatches.length !== 1 || endMatches.length !== 1) {
    throw new OperateError(
      'E_OPERATE_PROJECTION_DRIFT',
      `Projection markers for ${markerName} are malformed or duplicated.`,
      { markerName },
    );
  }
  const begin = beginMatches[0];
  const end = endMatches[0];
  const beginStart = begin.index ?? 0;
  const endStart = end.index ?? 0;
  if (endStart < beginStart + begin[0].length) {
    throw new OperateError(
      'E_OPERATE_PROJECTION_DRIFT',
      `Projection markers for ${markerName} are out of order.`,
      { markerName },
    );
  }
  const afterStart = endStart + end[0].length;
  return `${existing.slice(0, beginStart)}${block}${existing.slice(afterStart)}`;
}

function markdownProjectionSpecs(state: OperatingState): Array<{
  relativePath: string;
  markerName: string;
  managedContent: string;
}> {
  const registers = [...MARKDOWN_PROJECTIONS, ...READABLE_TREE_PROJECTIONS].map((projection) => ({
    relativePath: projection.relativePath,
    markerName: projection.markerName,
    managedContent: projection.render(state),
  }));
  const cycleArtifacts = [...state.cycles]
    .filter((cycle) => cycle.state === 'reviewable' || cycle.state === 'closed')
    .sort((left, right) => left.id.localeCompare(right.id))
    .flatMap((cycle) => [
      {
        relativePath: `${OPERATE_ROOT}/cycles/${cycle.id}/brief.md`,
        markerName: CYCLE_BRIEF_MARKER,
        managedContent: renderCycleBrief(state, cycle.id),
      },
      ...OPERATING_BOARD_ROLES.map((role) => ({
        relativePath: `${OPERATE_ROOT}/cycles/${cycle.id}/board/${role.id}.md`,
        markerName: BOARD_MARKER,
        managedContent: renderOperatingBoardReport(state, cycle.id, role),
      })),
    ]);
  return [...registers, ...cycleArtifacts];
}

export function renderOperatingProjectionFiles(state: OperatingState): OperatingProjectionFile[] {
  const stateFile: OperatingProjectionFile = {
    relativePath: STATE_PATH,
    content: `${canonicalize(state)}\n`,
  };
  const evidenceIndexFile: OperatingProjectionFile = {
    relativePath: EVIDENCE_INDEX_PATH,
    content: renderOperatingEvidenceIndex(state),
  };
  const markdownFiles = markdownProjectionSpecs(state).map((projection) => ({
    relativePath: projection.relativePath,
    markerName: projection.markerName,
    managedContent: projection.managedContent,
    content: spliceProjectionBlock('', projection.markerName, projection.managedContent),
  }));
  return [stateFile, evidenceIndexFile, ...markdownFiles];
}

async function inspectProjectionFile(
  projectRoot: string,
  expected: OperatingProjectionFile,
): Promise<OperatingProjectionDrift> {
  const expectedBytes = expected.markerName ? (expected.managedContent ?? '') : expected.content;
  const expectedDigest = sha256Digest(expectedBytes);
  const current = await readFile(path.join(projectRoot, expected.relativePath), 'utf8').catch(
    (error) => {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    },
  );
  if (current === null) {
    return {
      path: expected.relativePath,
      status: 'absent',
      expectedDigest,
      actualDigest: null,
      reason: 'Projection has not been generated.',
    };
  }
  if (!expected.markerName) {
    const actualDigest = sha256Digest(current);
    return actualDigest === expectedDigest
      ? { path: expected.relativePath, status: 'current', expectedDigest, actualDigest }
      : {
          path: expected.relativePath,
          status: 'drift',
          expectedDigest,
          actualDigest,
          reason: 'Canonical JSON bytes differ from event replay.',
        };
  }
  const section = managedSection(current, expected.markerName);
  if (!section) {
    return {
      path: expected.relativePath,
      status: 'drift',
      expectedDigest,
      actualDigest: sha256Digest(current),
      reason: 'Managed projection markers are missing.',
    };
  }
  if (section.malformed) {
    return {
      path: expected.relativePath,
      status: 'drift',
      expectedDigest,
      actualDigest: sha256Digest(current),
      reason: 'Managed projection markers are malformed or duplicated.',
    };
  }
  const actualDigest = sha256Digest(section.content);
  return actualDigest === expectedDigest
    ? { path: expected.relativePath, status: 'current', expectedDigest, actualDigest }
    : {
        path: expected.relativePath,
        status: 'drift',
        expectedDigest,
        actualDigest,
        reason: 'Generated projection rows differ from event replay.',
      };
}

export async function inspectOperatingProjectionDrift(input: {
  projectRoot: string;
  state: OperatingState;
}): Promise<OperatingProjectionDrift[]> {
  await assertOperatingArtifact('operating-state', input.state);
  const expected = renderOperatingProjectionFiles(input.state);
  return Promise.all(expected.map((file) => inspectProjectionFile(input.projectRoot, file)));
}

export async function assertOperatingProjectionsCurrent(input: {
  projectRoot: string;
  state: OperatingState;
}): Promise<void> {
  const drift = await inspectOperatingProjectionDrift(input);
  const mismatches = drift.filter((entry) => entry.status !== 'current');
  if (mismatches.length > 0) {
    throw new OperateError(
      'E_OPERATE_PROJECTION_DRIFT',
      `${mismatches.length} Operating Board projection(s) differ from event replay.`,
      { projections: mismatches },
    );
  }
}

export async function prepareOperatingProjectionPersistence(input: {
  projectRoot: string;
  state: OperatingState;
}): Promise<OperatingProjectionPreview> {
  await assertOperatingArtifact('operating-state', input.state);
  const rendered = renderOperatingProjectionFiles(input.state);
  const files: OperatingProjectionFile[] = [];
  for (const file of rendered) {
    if (!file.markerName) {
      files.push(file);
      continue;
    }
    const current = await readFile(path.join(input.projectRoot, file.relativePath), 'utf8').catch(
      (error) => {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') return '';
        throw error;
      },
    );
    files.push({
      ...file,
      content: spliceProjectionBlock(current, file.markerName, file.managedContent ?? ''),
    });
  }
  const changedPaths: string[] = [];
  for (const file of files) {
    const current = await readFile(path.join(input.projectRoot, file.relativePath)).catch(
      (error) => {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw error;
      },
    );
    if (current === null || sha256Digest(current) !== sha256Digest(file.content)) {
      changedPaths.push(file.relativePath);
    }
  }
  const drift = await inspectOperatingProjectionDrift(input);
  const stateDigest = canonicalDigest(input.state);
  const previewDigest = canonicalDigest({
    kind: 'operating-projection-preview',
    stateDigest,
    eventHead: input.state.eventHead,
    writes: files
      .filter((file) => changedPaths.includes(file.relativePath))
      .map((file) => ({
        path: file.relativePath,
        digest: sha256Digest(file.content),
      }))
      .sort((left, right) => left.path.localeCompare(right.path)),
  });
  return {
    stateDigest,
    eventHead: structuredClone(input.state.eventHead),
    previewDigest,
    files,
    changedPaths,
    drift,
  };
}

export async function persistOperatingProjections(input: {
  projectRoot: string;
  state: OperatingState;
  localRoot?: string;
  transactionId?: string;
  now?: string;
  revalidateEventHead?: () => Promise<OperatingEventHead>;
}): Promise<PersistOperatingProjectionResult> {
  const preview = await prepareOperatingProjectionPersistence(input);
  if (preview.changedPaths.length === 0) {
    return { ...preview, transactionId: null };
  }
  const changed = new Set(preview.changedPaths);
  const writes: JournalWrite[] = preview.files
    .filter((file) => changed.has(file.relativePath))
    .map((file) => ({
      relativePath: file.relativePath,
      content: file.content,
      mode: '0600',
    }));
  const transaction = await prepareJournalTransaction(input.projectRoot, {
    writes,
    eventHead: preview.eventHead,
    previewDigest: preview.previewDigest,
    localRoot: input.localRoot,
    transactionId: input.transactionId,
    now: input.now,
  });
  await applyJournalTransaction(input.projectRoot, transaction, {
    currentEventHead: preview.eventHead,
    revalidateEventHead: input.revalidateEventHead,
  });
  return {
    ...preview,
    transactionId: transaction.record.transactionId,
  };
}

export const OPERATING_PROJECTION_PATHS = {
  state: STATE_PATH,
  register: `${PROJECTION_ROOT}/register.md`,
  decisions: `${PROJECTION_ROOT}/decisions.md`,
  dataGaps: `${PROJECTION_ROOT}/data-gaps.md`,
  backlog: `${PROJECTION_ROOT}/backlog.md`,
  // FR5 readable tree at the workspace path getters (T-001).
  evidenceIndex: EVIDENCE_INDEX_PATH,
  brief: `${OPERATE_ROOT}/brief.md`,
  findings: `${OPERATE_ROOT}/findings.md`,
  readableDecisions: `${OPERATE_ROOT}/decisions.md`,
  gaps: `${OPERATE_ROOT}/gaps.md`,
  routes: `${OPERATE_ROOT}/routes.md`,
} as const;
