import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import {
  renderStylesheetOutputs,
  STYLESHEET_SOURCE_OUTPUTS,
  staleTypeScriptTargets,
  writeTypeScriptOutputs,
} from '../../scripts/typescript/compile-sources.mjs';

const root = new URL('../../', import.meta.url);
const { JSDOM, VirtualConsole } = createRequire(new URL('package.json', root))('jsdom');

function parseStyle(css) {
  const errors = [];
  const virtualConsole = new VirtualConsole();
  virtualConsole.on('jsdomError', (error) => errors.push(error.message));
  const dom = new JSDOM('<!doctype html><style></style><main></main>', { virtualConsole });
  dom.window.document.querySelector('style').textContent = css;
  const sheets = [...dom.window.document.styleSheets];
  const rules = sheets.flatMap((sheet) => [...sheet.cssRules]);
  dom.window.close();
  assert.deepEqual(errors, [], 'The actual installed DOM parser must accept every compiled style');
  assert.equal(sheets.length, 1, 'Parsing creates a genuine stylesheet');
  assert.ok(rules.length > 0, 'The stylesheet preserves its rules');
  return rules;
}

for (const name of ['studio-shell.css', 'diagram-editor.css'])
  test(`${name} at the existing public path parses in the installed DOM engine`, () => {
    parseStyle(readFileSync(new URL(`packages/artifact/lib/artifact/ui/${name}`, root), 'utf8'));
  });

function sourceFixture(t, css) {
  const directory = mkdtempSync(join(tmpdir(), 'studio-style-source-'));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const source = Object.keys(STYLESHEET_SOURCE_OUTPUTS)[0];
  const target = STYLESHEET_SOURCE_OUTPUTS[source];
  const packageRoot = join(directory, 'packages/artifact');
  mkdirSync(packageRoot, { recursive: true });
  writeFileSync(
    join(packageRoot, 'package.json'),
    readFileSync(new URL('packages/artifact/package.json', root)),
  );
  symlinkSync(fileURLToPath(new URL('node_modules', root)), join(directory, 'node_modules'), 'dir');
  for (const path of [source, target])
    mkdirSync(dirname(join(directory, path)), { recursive: true });
  writeFileSync(join(directory, source), css);
  return { directory, source, target };
}

const nestedFixture = `
.host, #host {
  color: var(--ink);
  .button { padding: 4px; }
  &[data-open] { .button { display: flex; } }
  @media (max-width: 680px) { .button { min-height: 44px; } }
}
`;

test('the stylesheet compiler lowers shared scopes, conditions and media without runtime imports', (t) => {
  const { directory, target } = sourceFixture(t, nestedFixture);
  const outputs = renderStylesheetOutputs({ root: directory });
  assert.deepEqual(Object.keys(outputs), [target]);
  assert.deepEqual(
    renderStylesheetOutputs({ root: directory }),
    outputs,
    'Output is deterministic',
  );
  assert.match(
    outputs[target],
    /^\/\* generated by scripts\/typescript\/compile-sources.mjs from studio-shell.source.css \*\//u,
  );
  assert.ok(!outputs[target].includes(directory), 'The output contains no machine paths');
  const rules = parseStyle(outputs[target]);
  assert.ok(
    rules.some((rule) => rule.selectorText?.includes(':is(.host,#host) .button')),
    'Grouping preserves the native nesting specificity',
  );
  assert.ok(
    rules.some((rule) => rule.selectorText?.includes('[data-open] .button')),
    'Conditional scope is retained',
  );
  const media = rules.find((rule) => /^\(max-width:\s*680px\)$/u.test(rule.conditionText));
  assert.ok(media, 'Nested media remains a real media rule');
  assert.equal(media.cssRules[0].style.getPropertyValue('min-height'), '44px');
});

test('CSS staleness uses exact source and emitted bytes; checking never overwrites output', (t) => {
  const { directory, source, target } = sourceFixture(t, nestedFixture);
  const outputs = renderStylesheetOutputs({ root: directory });
  assert.deepEqual(staleTypeScriptTargets({ root: directory, outputs }), [target]);
  assert.deepEqual(writeTypeScriptOutputs({ root: directory, outputs }), [target]);
  assert.deepEqual(staleTypeScriptTargets({ root: directory, outputs }), []);
  const first = readFileSync(join(directory, target), 'utf8');
  writeFileSync(join(directory, source), nestedFixture.replace('44px', '48px'));
  const next = renderStylesheetOutputs({ root: directory });
  assert.notEqual(next[target], first, 'The new source cannot reuse an old compiled style');
  assert.deepEqual(staleTypeScriptTargets({ root: directory, outputs: next }), [target]);
  assert.equal(
    readFileSync(join(directory, target), 'utf8'),
    first,
    'Stale detection preserves the existing output',
  );
  writeTypeScriptOutputs({ root: directory, outputs: next });
  writeFileSync(join(directory, target), '/* corrupted output */');
  assert.deepEqual(staleTypeScriptTargets({ root: directory, outputs: next }), [target]);
  assert.equal(readFileSync(join(directory, target), 'utf8'), '/* corrupted output */');
});

test('malformed CSS and a missing owned input fail compilation rather than using stale output', (t) => {
  const { directory, source, target } = sourceFixture(t, '.host { color: red; } }');
  writeFileSync(join(directory, target), '/* stale output */');
  assert.throws(() => renderStylesheetOutputs({ root: directory }), {
    code: 'E_STYLESHEET_WARNINGS',
  });
  rmSync(join(directory, source));
  assert.throws(() => renderStylesheetOutputs({ root: directory }), { code: 'ENOENT' });
  assert.equal(readFileSync(join(directory, target), 'utf8'), '/* stale output */');
});

test('the actual exported CSS equals the owned compiler output at the original public path', () => {
  const source = Object.keys(STYLESHEET_SOURCE_OUTPUTS)[0];
  const target = STYLESHEET_SOURCE_OUTPUTS[source];
  assert.equal(target, 'packages/artifact/lib/artifact/ui/studio-shell.css');
  assert.match(readFileSync(new URL(source, root), 'utf8'), /@media \(max-width: 680px\)/u);
  const compiled = renderStylesheetOutputs({ root: fileURLToPath(root) });
  assert.equal(readFileSync(new URL(target, root), 'utf8'), compiled[target]);
  const manifest = JSON.parse(
    readFileSync(new URL('packages/artifact/package.json', root), 'utf8'),
  );
  assert.equal(manifest.exports['./studio-shell.css'], './lib/artifact/ui/studio-shell.css');
});
