# Estimation Guide

This guide defines how story points, complexity, and effort hours are used in this project. All estimates produced by `planr estimate` follow this rubric.

## Story Points (Fibonacci Scale)

Story points measure **relative complexity**, not calendar time. Use the Fibonacci sequence to force clear distinctions between small and large work.

| Points | Label          | Description                         | Typical Scope                   |
| ------ | -------------- | ----------------------------------- | ------------------------------- |
| **1**  | Trivial        | Config change, typo fix, one-liner  | Minutes to 1 hour               |
| **2**  | Small          | Single-file change, well-understood | 1-3 hours                       |
| **3**  | Moderate       | A few files, clear approach         | Half a day                      |
| **5**  | Medium         | Multiple files, some unknowns       | 1-2 days                        |
| **8**  | Large          | Cross-cutting change, needs design  | 2-4 days                        |
| **13** | Very Large     | Multi-system, significant unknowns  | 1-2 weeks                       |
| **21** | Epic-scale     | Major feature or rewrite, high risk | 2+ weeks (consider splitting)   |

### Rules of Thumb

- If it's **> 13 points**, break it into smaller tasks before implementing
- Points reflect **complexity + unknowns**, not just lines of code
- A 5-point task with a clear path is easier than a 3-point task with unknowns
- Compare against previously completed tasks for consistency

## Complexity Levels

| Level      | Meaning                                                                                   |
| ---------- | ----------------------------------------------------------------------------------------- |
| **Low**    | Well-understood domain, clear requirements, existing patterns to follow                    |
| **Medium** | Some unknowns, may need research or new patterns, moderate integration                     |
| **High**   | Significant unknowns, new technology, cross-system impact, security/performance-critical   |

## Risk Factors

Each estimate includes 1-5 risk factors. Common categories:

- **Technical** — new technology, performance constraints, complex algorithms
- **Integration** — external APIs, third-party dependencies, cross-team coordination
- **Requirements** — ambiguous scope, evolving specs, edge cases
- **Infrastructure** — deployment complexity, scaling needs, data migration
- **Knowledge** — unfamiliar domain, missing expertise, documentation gaps

## Hours vs Points

Points and hours serve different purposes:

- **Points** = relative sizing for sprint planning and velocity tracking
- **Hours** = rough developer-time estimate for scheduling and capacity

They don't convert linearly. A 5-point task might take 8 hours for a junior dev or 4 hours for a senior. Use hours as a planning guide, not a commitment.

## Calibration

Run `planr estimate --calibrate` to compare past estimates against completed work. Over time, this helps the team:

- Identify systematic over/under-estimation
- Build a shared understanding of what "5 points" means
- Improve future estimate accuracy

## Using Estimates

```bash
planr estimate TASK-001              # View estimate for a single artifact
planr estimate TASK-001 --save       # Save estimate to the artifact
planr estimate --epic EPIC-001       # Estimate all tasks under an epic
planr estimate --calibrate           # Review estimation accuracy
```

---
_Generated by `planr init`. Edit this file to match your team's conventions._
