export type OperateErrorCodeV2 =
  | 'CYCLE_NOT_FOUND'
  | 'CYCLE_TERMINAL'
  | 'ASSIGNMENT_NOT_AVAILABLE'
  | 'ASSIGNMENT_ALREADY_CLAIMED'
  | 'ASSIGNMENT_ALREADY_SUBMITTED'
  | 'ACTION_REVISION_MISMATCH'
  | 'RESULT_CONTRACT_INVALID'
  | 'SUBMISSION_ID_CONFLICT'
  | 'CAPABILITY_DENIED'
  | 'REVIEW_NOT_FOUND'
  | 'REVIEW_NOT_PENDING'
  | 'REVIEW_NOT_AUTHORIZED'
  | 'STATE_TRANSITION_INVALID'
  | 'ARTIFACT_NOT_FOUND'
  | 'CONTRACT_VERSION_UNSUPPORTED'
  | 'CONCURRENT_MODIFICATION'
  | 'OPERATING_SCOPE_INVALID'
  | 'DOMAIN_CONTRACT_UNSUPPORTED'
  | 'OPERATE_STORE_CORRUPT'
  | 'OPERATE_STORE_INCOMPATIBLE'
  | 'OPERATE_STORE_CONFLICT'
  | 'OPERATE_SUBJECT_NOT_FOUND'
  | 'OPERATION_CONFLICT'
  | 'OPERATION_UNCERTAIN'
  | 'ROLLBACK_NOT_ELIGIBLE'
  | 'APPROVAL_INVALID'
  | 'APPROVAL_REQUIRED'
  | 'POLICY_EVALUATION_REJECTED'
  | 'E_OPERATE_PLANNING_ACCESS'
  | 'E_OPERATE_PLANNING_BINDING'
  | 'E_OPERATE_PLANNING_CONCURRENT'
  | 'E_OPERATE_PLANNING_CONFIRMATION'
  | 'E_OPERATE_PLANNING_CONFLICT'
  | 'E_OPERATE_PLANNING_CUSTODY'
  | 'E_OPERATE_PLANNING_INVALID'
  | 'E_OPERATE_PLANNING_PATH'
  | 'E_OPERATE_PLANNING_ROUTE'
  | 'E_OPERATE_PLANNING_STALE'
  | 'E_OPERATE_PLANNING_STATE'
  | 'E_OPERATE_ORIGIN_INVALID'
  | 'E_PROVENANCE_CONFLICT';

/** Closed application error used by the stable client facade and its lifecycle services. */
export class OperateClientError extends Error {
  constructor(
    readonly code: OperateErrorCodeV2,
    message: string,
    readonly retryable: boolean,
    readonly context: Record<string, string | number | boolean | null> = {},
  ) {
    super(message);
    this.name = code;
  }
}
