export const DIAGRAM_ERROR_CODES = Object.freeze({
  ACCESSIBILITY_INVALID: 'E_DIAGRAM_ACCESSIBILITY_INVALID',
  GRAMMAR_AMBIGUOUS: 'E_DIAGRAM_GRAMMAR_AMBIGUOUS',
  GRAMMAR_RULE_INVALID: 'E_DIAGRAM_GRAMMAR_RULE_INVALID',
  GRAMMAR_UNKNOWN: 'E_DIAGRAM_GRAMMAR_UNKNOWN',
  MERMAID_INVALID: 'E_DIAGRAM_MERMAID_INVALID',
  MERMAID_TOO_LARGE: 'E_DIAGRAM_MERMAID_TOO_LARGE',
  OUTPUT_CONFLICT: 'E_DIAGRAM_OUTPUT_CONFLICT',
  OUTPUT_ESCAPE: 'E_DIAGRAM_OUTPUT_ESCAPE',
  OUTPUT_LOCKED: 'E_DIAGRAM_OUTPUT_LOCKED',
  PNG_INVALID: 'E_DIAGRAM_PNG_INVALID',
  PROJECTION_UNSUPPORTED: 'E_DIAGRAM_PROJECTION_UNSUPPORTED',
  REFERENCE_CUSTODY_INVALID: 'E_DIAGRAM_REFERENCE_CUSTODY_INVALID',
  RENDER_FAILED: 'E_DIAGRAM_RENDER_FAILED',
  RESOURCE_BUDGET_EXCEEDED: 'E_DIAGRAM_RESOURCE_BUDGET_EXCEEDED',
  SCENE_INVALID: 'E_DIAGRAM_SCENE_INVALID',
  SCHEMA_INVALID: 'E_DIAGRAM_SCHEMA_INVALID',
  SOURCE_CONFLICT: 'E_DIAGRAM_SOURCE_CONFLICT',
});

export class DiagramError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = 'DiagramError';
    this.code = code;
    this.details = Object.freeze({ ...details });
  }
}

export function diagramFail(code, message, details) {
  throw new DiagramError(code, message, details);
}
