import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  createOperateV2DevelopmentSnapshot,
  USER_OWNED_EXCLUDED_PATHS,
} from '../../scripts/check-operate-runtime-purity.mjs';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const manifestPaths = [
  'lib/generated/protocol-projection.json',
  'lib/generated/domain-projections/artifact.json',
  'lib/generated/domain-projections/design.json',
  'lib/generated/domain-projections/operate.json',
];

function run(command, args, cwd) {
  const result = spawnSync(command, args, { cwd, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  assert.equal(result.status, 0, `${command} ${args.join(' ')}\n${result.stderr}`);
  return result.stdout.trim();
}

test('development snapshot carries ignored projection outputs with exact manifest custody', async (t) => {
  const temporaryRoot = mkdtempSync(join(tmpdir(), 'planr-development-snapshot-'));
  t.after(() => rmSync(temporaryRoot, { recursive: true, force: true }));
  const source = join(temporaryRoot, 'source');
  mkdirSync(source);
  const topLevel = run('git', ['rev-parse', '--show-toplevel'], packageRoot);
  const prefix = run('git', ['rev-parse', '--show-prefix'], packageRoot);
  const archive = join(temporaryRoot, 'source.tar');
  run(
    'git',
    [
      'archive',
      '--format=tar',
      '--output',
      archive,
      prefix ? `HEAD:${prefix.replace(/\/$/, '')}` : 'HEAD',
    ],
    topLevel,
  );
  run('tar', ['-xf', archive, '-C', source], temporaryRoot);

  const entries = manifestPaths.flatMap((path) => {
    copyFileSync(join(packageRoot, path), join(source, path));
    return JSON.parse(readFileSync(join(packageRoot, path), 'utf8')).entries;
  });
  for (const { target } of entries) {
    mkdirSync(dirname(join(source, target)), { recursive: true });
    copyFileSync(join(packageRoot, target), join(source, target));
  }
  copyFileSync(join(topLevel, 'package-lock.json'), join(source, 'package-lock.json'));
  writeFileSync(
    join(source, '.gitignore'),
    `${entries.map(({ target }) => `/${target}`).join('\n')}\n/lib/design/private.mjs\n`,
  );
  run('git', ['init', '--quiet'], source);
  run('git', ['add', '--all'], source);
  run(
    'git',
    [
      '-c',
      'user.name=Snapshot Test',
      '-c',
      'user.email=snapshot@example.invalid',
      '-c',
      'commit.gpgsign=false',
      'commit',
      '--quiet',
      '-m',
      'Committed source without generated outputs',
    ],
    source,
  );
  const tracked = new Set(run('git', ['ls-files'], source).split('\n'));
  for (const { target } of entries)
    assert.equal(tracked.has(target), false, `${target} must be absent from Git`);
  writeFileSync(join(source, 'lib/design/private.mjs'), 'private unrelated scratch data\n');
  for (const path of USER_OWNED_EXCLUDED_PATHS)
    writeFileSync(join(source, path), 'unrelated user-owned change\n');

  await t.test(
    'restores every generated byte without copying unrelated or excluded worktree bytes',
    () => {
      const destination = join(temporaryRoot, 'snapshot');
      const snapshot = createOperateV2DevelopmentSnapshot(destination, { sourceRoot: source });
      for (const { target, sha256 } of entries) {
        assert.equal(
          createHash('sha256')
            .update(readFileSync(join(destination, target)))
            .digest('hex'),
          sha256,
          target,
        );
        assert.ok(snapshot.overlays.includes(target));
      }
      for (const path of manifestPaths)
        assert.deepEqual(readFileSync(join(destination, path)), readFileSync(join(source, path)));
      assert.equal(existsSync(join(destination, 'lib/design/private.mjs')), false);
      for (const proof of snapshot.excludedProof) {
        assert.equal(proof.snapshotSha256, proof.headSha256);
        assert.notEqual(proof.snapshotSha256, proof.worktreeSha256);
      }
    },
  );

  const generatedPath = 'lib/design/browser-audit.mjs';
  const original = readFileSync(join(source, generatedPath));
  await t.test(
    'rejects stale generated bytes instead of certifying an inconsistent snapshot',
    () => {
      writeFileSync(join(source, generatedPath), 'stale generated output\n');
      try {
        assert.throws(
          () =>
            createOperateV2DevelopmentSnapshot(join(temporaryRoot, 'stale'), {
              sourceRoot: source,
            }),
          /Development projection digest mismatch: lib\/design\/browser-audit\.mjs/,
        );
      } finally {
        writeFileSync(join(source, generatedPath), original);
      }
    },
  );

  await t.test('rejects a symlinked projection even when the target bytes match', () => {
    const target = join(temporaryRoot, 'outside.mjs');
    writeFileSync(target, original);
    rmSync(join(source, generatedPath));
    symlinkSync(target, join(source, generatedPath));
    try {
      assert.throws(
        () =>
          createOperateV2DevelopmentSnapshot(join(temporaryRoot, 'symlink'), {
            sourceRoot: source,
          }),
        /Development projection contains a symlink/,
      );
    } finally {
      rmSync(join(source, generatedPath));
      writeFileSync(join(source, generatedPath), original);
    }
  });

  await t.test('rejects a manifest path escape before writing outside the snapshot', () => {
    const path = join(source, manifestPaths[2]);
    const bytes = readFileSync(path);
    const manifest = JSON.parse(bytes);
    manifest.entries[0].target = '../escaped.mjs';
    writeFileSync(path, JSON.stringify(manifest));
    try {
      assert.throws(
        () =>
          createOperateV2DevelopmentSnapshot(join(temporaryRoot, 'escape'), { sourceRoot: source }),
        /Invalid development projection entry/,
      );
      assert.equal(existsSync(join(temporaryRoot, 'escaped.mjs')), false);
    } finally {
      writeFileSync(path, bytes);
    }
  });
});
