import type { Command } from 'commander';
import {
  type DiagramSourceChoice,
  diagramGallery,
  inspectDiagramInput,
  renderDiagramInput,
  rerenderDiagramInput,
} from '../../../services/diagram-pipeline-service.js';
import { presentDiagramGallery, presentDiagramResult } from './presentation.js';

interface RenderOptions {
  json?: boolean;
  output?: string;
  slug?: string;
}

interface InspectOptions {
  json?: boolean;
}

interface GalleryOptions {
  json?: boolean;
  type?: string;
}

interface RerenderOptions {
  accept?: string;
  json?: boolean;
}

function projectDir(program: Command): string {
  return program.opts().projectDir as string;
}

function sourceChoice(value?: string): DiagramSourceChoice | undefined {
  if (value === undefined) return undefined;
  if (['ir', 'mermaid', 'excalidraw'].includes(value)) return value as DiagramSourceChoice;
  const error = new Error('Diagram source must be ir, mermaid, or excalidraw.');
  error.name = 'E_DIAGRAM_SOURCE_INVALID';
  throw error;
}

export function registerDiagramCommand(program: Command): void {
  const diagram = program
    .command('diagram')
    .description('Create, verify, inspect, and rerender offline professional diagrams');

  diagram
    .command('render')
    .argument('<input>', 'canonical .planr-diagram.json or Mermaid source')
    .description('Render a verified offline diagram set')
    .option('--slug <slug>', 'override the output slug')
    .option('--output <directory>', 'output root; defaults to the repository root')
    .option('--json', 'output one stable machine envelope')
    .action(async (input: string, options: RenderOptions) => {
      presentDiagramResult(
        await renderDiagramInput({
          projectDir: projectDir(program),
          input,
          output: options.output,
          slug: options.slug,
        }),
        Boolean(options.json),
      );
    });

  for (const [name, description, check] of [
    ['inspect', 'Inspect source or generated manifest custody', false],
    ['check', 'Validate source or verify generated bytes against their manifest', true],
  ] as const) {
    diagram
      .command(name)
      .argument('<input-or-manifest>', 'diagram source, manifest, or generated diagram directory')
      .description(description)
      .option('--json', 'output one stable machine envelope')
      .action(async (input: string, options: InspectOptions) => {
        presentDiagramResult(
          await inspectDiagramInput({
            projectDir: projectDir(program),
            input,
            check,
          }),
          Boolean(options.json),
        );
      });
  }

  diagram
    .command('gallery')
    .description('List the searchable diagram grammar and primitive gallery')
    .option('--type <type>', 'filter by grammar, alias, or layout family')
    .option('--json', 'output one stable machine envelope')
    .action(async (options: GalleryOptions) => {
      presentDiagramGallery(await diagramGallery(options.type), Boolean(options.json));
    });

  diagram
    .command('rerender')
    .argument('<manifest>', 'generated diagram manifest')
    .description('Rerender after an intentional source edit')
    .option('--accept <source>', 'choose ir, mermaid, or excalidraw when source branches conflict')
    .option('--json', 'output one stable machine envelope')
    .action(async (manifest: string, options: RerenderOptions) => {
      presentDiagramResult(
        await rerenderDiagramInput({
          projectDir: projectDir(program),
          manifest,
          accept: sourceChoice(options.accept),
        }),
        Boolean(options.json),
      );
    });
}
