import path from 'node:path';
import type { Command } from 'commander';
import { createGenerator, createGenerators } from '../../generators/generator-factory.js';
import type { ArtifactCollection, GenerationScope, TargetCLI } from '../../models/types.js';
import { loadConfig } from '../../services/config-service.js';
import { ensureDir, fileExists, writeFile } from '../../utils/fs.js';
import { logger } from '../../utils/logger.js';

/**
 * Filenames generated by openplanr v1.5.0 (before the planr-pipeline rename).
 * If detected in a project, we surface a one-line cleanup hint — but never
 * auto-delete, to avoid surprising users with destructive behavior.
 */
const LEGACY_CURSOR_RULES = [
  'openplanr-pipeline.mdc',
  'openplanr-pipeline-plan.mdc',
  'openplanr-pipeline-ship.mdc',
];
const LEGACY_CLAUDE_REF = 'openplanr-pipeline.md';

const VALID_SCOPES: GenerationScope[] = ['agile', 'pipeline', 'all'];

export function registerRulesCommand(program: Command) {
  program
    .command('rules')
    .description('Generate AI agent rule files')
    .command('generate')
    .description('Generate rule files for configured AI CLIs')
    .option('--target <target>', 'specific target: cursor, claude, codex, or all', 'all')
    .option('--scope <scope>', 'rule set to generate: agile (default), pipeline, or all', 'agile')
    .option('--dry-run', 'show what would be generated without writing files', false)
    .action(async (opts) => {
      const projectDir = program.opts().projectDir as string;
      const config = await loadConfig(projectDir);

      // Validate --scope.
      const scope = opts.scope as GenerationScope;
      if (!VALID_SCOPES.includes(scope)) {
        logger.error(
          `Invalid --scope value "${opts.scope}". Expected one of: ${VALID_SCOPES.join(', ')}.`,
        );
        process.exit(1);
      }

      // Empty artifact collection — generators read from disk as needed
      const artifacts: ArtifactCollection = {
        epics: [],
        features: [],
        stories: [],
        tasks: [],
      };

      const generators =
        opts.target === 'all'
          ? createGenerators(config, projectDir)
          : [createGenerator(opts.target as TargetCLI, config, projectDir)];

      logger.heading(`Generating AI Agent Rules — scope=${scope}`);
      let totalFiles = 0;

      for (const generator of generators) {
        generator.setScope(scope);
        const files = await generator.generate(artifacts);
        logger.info(`${generator.getTargetName()}: ${files.length} file(s)`);

        for (const file of files) {
          const fullPath = path.join(projectDir, file.path);
          if (opts.dryRun) {
            logger.dim(`  [dry-run] ${file.path}`);
          } else {
            await ensureDir(path.dirname(fullPath));
            await writeFile(fullPath, file.content);
            logger.dim(`  ${file.path}`);
          }
          totalFiles++;
        }
      }

      logger.success(`${opts.dryRun ? 'Would generate' : 'Generated'} ${totalFiles} rule file(s)`);

      // Legacy cleanup hint (planr-pipeline rename, v1.5.1)
      if (!opts.dryRun) {
        const stale: string[] = [];
        for (const name of LEGACY_CURSOR_RULES) {
          const p = path.join(projectDir, config.outputPaths.cursorRules, name);
          if (await fileExists(p)) stale.push(p);
        }
        const claudeStale = path.join(
          projectDir,
          config.outputPaths.claudeConfig,
          LEGACY_CLAUDE_REF,
        );
        if (await fileExists(claudeStale)) stale.push(claudeStale);
        if (stale.length > 0) {
          logger.dim('');
          logger.warn(
            `Detected ${stale.length} legacy rule file(s) from before the planr-pipeline rename:`,
          );
          for (const p of stale) logger.dim(`  ${p}`);
          logger.dim('');
          logger.dim('  Safe to delete — they were generated by an earlier CLI version.');
          logger.dim('  Not auto-deleted to avoid surprising users.');
        }
      }
    });
}
