import chalk from 'chalk';
import type { Command } from 'commander';
import { loadConfig } from '../../services/config-service.js';
import {
  collectDeliveryStatus,
  type DeliveryItem,
  type DeliveryStatus,
} from '../../services/delivery-status-service.js';
import { colorByPercent } from '../../utils/format.js';
import { display, logger } from '../../utils/logger.js';

export function registerStatusCommand(program: Command) {
  program
    .command('status')
    .argument('[scope]', 'limit the report to one spec/epic/feature id or slug')
    .description(
      'Whole-project delivery report — every spec/backlog/quick-task by status, optionally cross-referenced with GitHub PRs + Linear',
    )
    .option(
      '--github',
      'live-resolve linked GitHub issue state + correlate PRs by id (needs `gh` auth)',
    )
    .option(
      '--linear',
      'live-resolve Linear issue state (else uses reconciled state from frontmatter)',
    )
    .option('--md', 'output the delivery report as markdown (paste-ready)')
    .option('--json', 'output the delivery report as JSON')
    .option('--all', 'show all items without truncation (terminal view)')
    .action(async (scope: string | undefined, opts) => {
      const projectDir = program.opts().projectDir as string;
      const config = await loadConfig(projectDir);

      const status = await collectDeliveryStatus(projectDir, config, {
        scope,
        github: !!opts.github,
        linear: !!opts.linear,
      });

      if (opts.json) {
        display.line(JSON.stringify(status, (k, v) => (k === '_linearId' ? undefined : v), 2));
        return;
      }
      if (opts.md) {
        display.line(renderMarkdown(status));
        return;
      }
      renderTerminal(status, { showAll: !!opts.all, config });
    });
}

// ── status presentation ──────────────────────────────────────────────────────
const MD_ICON: Record<string, string> = {
  done: '✅',
  closed: '✅',
  decomposed: '🔄',
  'in-progress': '🔄',
  decomposing: '⏳',
  shaping: '✏️',
  promoted: '↗',
  superseded: '⚫',
  blocked: '⛔',
  pending: '•',
  open: '•',
};
const mdIcon = (s: string) => MD_ICON[(s || '').toLowerCase()] ?? '•';

function statusColor(s: string): (t: string) => string {
  const k = (s || '').toLowerCase();
  if (k === 'done' || k === 'closed') return chalk.green;
  if (k === 'blocked') return chalk.red;
  if (k === 'superseded') return chalk.dim;
  if (k === 'pending' || k === 'open') return chalk.dim;
  return chalk.yellow; // in-progress / decomposed / shaping / promoted …
}

function ghCell(i: DeliveryItem): string {
  const pr = i.github?.pr;
  if (pr) return `#${pr.number}${pr.merged ? ' ✓' : ''}`;
  if (i.github?.issue)
    return `issue #${i.github.issue}${i.github.issueState ? ` (${i.github.issueState})` : ''}`;
  return '—';
}
function linCell(i: DeliveryItem): string {
  if (!i.linear) return '—';
  return i.linear.state ? `${i.linear.identifier} (${i.linear.state})` : i.linear.identifier;
}
function progCell(i: DeliveryItem): string {
  return i.progress && i.progress.total > 0 ? `${i.progress.done}/${i.progress.total}` : '';
}

export function renderMarkdown(s: DeliveryStatus): string {
  const L: string[] = [];
  L.push(`# ${s.projectName} — Delivery Status`, '');
  L.push('> Generated by `planr status --md`. Source of truth: `.planr/` frontmatter.', '');
  L.push('## Summary', '');
  for (const row of s.summary) {
    const addressed = row.addressed > 0 ? ` + ${row.addressed} promoted/superseded` : '';
    L.push(`- **${row.label}:** ${row.done} done${addressed} — ${row.total} total`);
  }
  L.push(`- **Outstanding:** ${s.outstanding.length === 0 ? 'none' : s.outstanding.length}`, '');

  for (const label of s.order) {
    const items = s.groups[label];
    L.push(`## ${label}`, '');
    L.push('| ID | Status | Title | Progress | PR | Linear |');
    L.push('|----|--------|-------|----------|----|--------|');
    for (const i of items) {
      const title = i.title.replace(/\|/g, '\\|');
      L.push(
        `| ${i.id} | ${mdIcon(i.status)} ${i.status} | ${title} | ${progCell(i)} | ${ghCell(i)} | ${linCell(i)} |`,
      );
    }
    L.push('');
  }

  L.push('## Outstanding work', '');
  if (s.outstanding.length === 0) {
    L.push('None — every item is done or addressed (promoted/superseded).');
  } else {
    for (const i of s.outstanding) L.push(`- **${i.id}** ${i.title} — _${i.status}_`);
  }
  if (s.warnings.length) {
    L.push('', '## Notes', '');
    for (const w of s.warnings) L.push(`- ${w}`);
  }
  return L.join('\n');
}

function renderTerminal(
  s: DeliveryStatus,
  ctx: { showAll: boolean; config: { targets: string[]; outputPaths: { agile: string } } },
): void {
  logger.heading(`Delivery Status — ${s.projectName}  (${s.mode})`);
  display.blank();

  for (const label of s.order) {
    const items = s.groups[label];
    const doneN = items.filter((i) => i.done).length;
    const addressedN = items.filter((i) => i.addressed).length;
    const resolvedPct = items.length ? Math.round(((doneN + addressedN) / items.length) * 100) : 0;
    const addressedTxt = addressedN > 0 ? ` (+${addressedN} promoted/superseded)` : '';
    display.line(
      `  ${chalk.bold(label)}: ${colorByPercent(`${doneN}/${items.length} done`, resolvedPct)}${chalk.dim(addressedTxt)}`,
    );
    const list = ctx.showAll ? items : items.slice(0, 12);
    for (const i of list) {
      const st = statusColor(i.status)(`[${i.status}]`);
      const prog = progCell(i) ? chalk.dim(` ${progCell(i)}`) : '';
      const gh = i.github?.pr || i.github?.issue ? chalk.cyan(`  ${ghCell(i)}`) : '';
      const lin = i.linear ? chalk.magenta(`  ${linCell(i)}`) : '';
      display.line(`    ${i.id}  ${i.title}  ${st}${prog}${gh}${lin}`);
    }
    if (!ctx.showAll && items.length > 12)
      display.line(chalk.dim(`    … and ${items.length - 12} more (use --all)`));
    display.blank();
  }

  // Outstanding work
  if (s.outstanding.length === 0) {
    display.line(
      `  ${chalk.green('●')} Outstanding work: none — every item is done or addressed (promoted/superseded).`,
    );
  } else {
    display.line(`  ${chalk.yellow('●')} Outstanding work: ${s.outstanding.length}`);
    for (const i of ctx.showAll ? s.outstanding : s.outstanding.slice(0, 12)) {
      display.line(`    ${i.id}  ${i.title}  ${statusColor(i.status)(`[${i.status}]`)}`);
    }
    if (!ctx.showAll && s.outstanding.length > 12)
      display.line(chalk.dim(`    … and ${s.outstanding.length - 12} more`));
  }

  for (const w of s.warnings) {
    display.blank();
    logger.dim(`  ⚠ ${w}`);
  }

  display.blank();
  logger.dim(
    `Tip: --md for a paste-ready report · --json for machine output · --github --linear for live status`,
  );
  logger.dim(`Artifacts: ${ctx.config.outputPaths.agile}/`);
}
