import {
  assertDiagramReviewBundle,
  assertDiagramReviewFeedback,
  assertDiagramWorkspaceContract,
  DIAGRAM_WORKSPACE_API,
  DIAGRAM_WORKSPACE_CREATE_SCHEMA,
  DIAGRAM_WORKSPACE_EVENT_SCHEMA,
  DIAGRAM_WORKSPACE_MAX_BYTES,
  DIAGRAM_WORKSPACE_MAX_EVENT_BYTES,
  DIAGRAM_WORKSPACE_REVISION_SCHEMA,
  DIAGRAM_WORKSPACE_SCHEMA,
  DIAGRAM_WORKSPACE_VERSION,
  diagramReviewBundleDigest,
} from '@openplanr/protocol/diagram-review-contracts';
import { createEncryptedWorkspaceClient } from '../encrypted-workspace-client.mjs';

export const DIAGRAM_SHARE_BASE_URL = 'https://share.openplanr.dev';
const client = createEncryptedWorkspaceClient({
  domain: 'openplanr-diagram-workspace/v1',
  apiPath: DIAGRAM_WORKSPACE_API,
  reviewPath: '/diagram',
  label: 'Diagram',
  compatibilityCode: 'E_DIAGRAM_SHARE_UNSUPPORTED',
  compatibilityMessage:
    'This sharing service does not support native diagram workspaces. Upgrade the hosted service before retrying the saved operation.',
  defaultBaseUrl: DIAGRAM_SHARE_BASE_URL,
  version: DIAGRAM_WORKSPACE_VERSION,
  maxBytes: DIAGRAM_WORKSPACE_MAX_BYTES,
  maxEventBytes: DIAGRAM_WORKSPACE_MAX_EVENT_BYTES,
  schemas: {
    create: DIAGRAM_WORKSPACE_CREATE_SCHEMA,
    event: DIAGRAM_WORKSPACE_EVENT_SCHEMA,
    revision: DIAGRAM_WORKSPACE_REVISION_SCHEMA,
    workspace: DIAGRAM_WORKSPACE_SCHEMA,
  },
  assertContract: assertDiagramWorkspaceContract,
  assertBundle: assertDiagramReviewBundle,
  assertFeedback: assertDiagramReviewFeedback,
  bundleDigest: diagramReviewBundleDigest,
});
export const {
  encodeWorkspaceBytes,
  decodeWorkspaceBytes,
  newWorkspaceToken,
  newWorkspaceId,
  normalizeWorkspaceBase,
  workspaceReviewUrl,
  deriveWorkspaceAuthentication,
  canonicalWorkspacePublicKey,
  createWorkspaceSigner,
  signWorkspaceValue,
  verifyWorkspaceSignature,
  workspaceEnvelopeDigest,
  prepareWorkspace,
  commitWorkspace,
  getWorkspace,
  listWorkspaceRevisions,
  decryptWorkspaceRevision,
  prepareWorkspaceMutation,
  commitWorkspaceMutation,
  publishWorkspace,
  rotateWorkspace,
  manageWorkspace,
  prepareWorkspaceEvent,
  appendWorkspaceEvent,
  readWorkspaceEvents,
} = client;
