import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import {
  createChecklist,
  getChecklistPath,
  getChecklistProgress,
  parseChecklistItems,
  readChecklist,
  resetChecklist,
  toggleChecklistItems,
} from '../../src/services/checklist-service.js';
import { createDefaultConfig } from '../../src/services/config-service.js';
import { ensureDir } from '../../src/utils/fs.js';

const SAMPLE_CHECKLIST = `# Agile Development Guide — TestProject

> Generated by Planr on 2026-03-28

## Phase 1: Requirements Analysis

| # | Activity | Command | Status |
|---|----------|---------|--------|
| 1 | Create Epic | \`planr epic create\` | [x] |
| 2 | Create Features from Epic | \`planr feature create --epic <ID>\` | [x] |
| 3 | Create User Stories from Features | \`planr story create --feature <ID>\` | [ ] |

## Phase 2: Technical Design

| # | Activity | Artifact | Status |
|---|----------|----------|--------|
| 4 | UML Sequence Diagrams | \`.planr/diagrams/\` | [ ] |
| 5 | C4 Architecture Diagrams | \`.planr/diagrams/\` | [ ] |`;

describe('getChecklistPath', () => {
  it('returns path ending in checklists/AGILE-DEVELOPMENT-GUIDE.md', () => {
    const config = createDefaultConfig('test');
    const p = getChecklistPath('/project', config);
    expect(p).toBe('/project/.planr/checklists/AGILE-DEVELOPMENT-GUIDE.md');
  });
});

describe('createChecklist / readChecklist / resetChecklist', () => {
  let tmpDir: string;
  let config: ReturnType<typeof createDefaultConfig>;

  beforeAll(async () => {
    tmpDir = mkdtempSync(join(tmpdir(), 'planr-checklist-'));
    config = createDefaultConfig('test');
    await ensureDir(join(tmpDir, config.outputPaths.agile, 'checklists'));
  });

  afterAll(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('creates a checklist file', async () => {
    const filePath = await createChecklist(tmpDir, config);
    expect(filePath).toContain('AGILE-DEVELOPMENT-GUIDE.md');
  });

  it('reads the created checklist', async () => {
    const content = await readChecklist(tmpDir, config);
    expect(content).not.toBeNull();
    expect(content).toContain('Agile');
  });

  it('returns null when checklist does not exist', async () => {
    const emptyDir = mkdtempSync(join(tmpdir(), 'planr-empty-'));
    await ensureDir(join(emptyDir, config.outputPaths.agile, 'checklists'));
    const content = await readChecklist(emptyDir, config);
    expect(content).toBeNull();
    rmSync(emptyDir, { recursive: true, force: true });
  });

  it('resetChecklist recreates the checklist', async () => {
    const filePath = await resetChecklist(tmpDir, config);
    expect(filePath).toContain('AGILE-DEVELOPMENT-GUIDE.md');
    const content = await readChecklist(tmpDir, config);
    expect(content).not.toBeNull();
  });
});

describe('parseChecklistItems', () => {
  it('should parse all checklist items from markdown', () => {
    const items = parseChecklistItems(SAMPLE_CHECKLIST);
    expect(items).toHaveLength(5);
  });

  it('should parse checked items correctly', () => {
    const items = parseChecklistItems(SAMPLE_CHECKLIST);
    expect(items[0]).toMatchObject({ index: 1, activity: 'Create Epic', done: true });
    expect(items[1]).toMatchObject({ index: 2, activity: 'Create Features from Epic', done: true });
  });

  it('should parse unchecked items correctly', () => {
    const items = parseChecklistItems(SAMPLE_CHECKLIST);
    expect(items[2]).toMatchObject({
      index: 3,
      activity: 'Create User Stories from Features',
      done: false,
    });
    expect(items[3]).toMatchObject({ index: 4, activity: 'UML Sequence Diagrams', done: false });
  });

  it('should store line indices for toggling', () => {
    const items = parseChecklistItems(SAMPLE_CHECKLIST);
    for (const item of items) {
      expect(item.lineIndex).toBeGreaterThan(0);
    }
  });

  it('should return empty array for content with no checklist items', () => {
    const items = parseChecklistItems('# Just a heading\n\nSome text.');
    expect(items).toHaveLength(0);
  });
});

describe('toggleChecklistItems', () => {
  it('should toggle unchecked items to checked', () => {
    const items = parseChecklistItems(SAMPLE_CHECKLIST);
    const updated = toggleChecklistItems(SAMPLE_CHECKLIST, new Set([3]), items);
    const updatedItems = parseChecklistItems(updated);
    expect(updatedItems[2].done).toBe(true);
  });

  it('should toggle checked items to unchecked', () => {
    const items = parseChecklistItems(SAMPLE_CHECKLIST);
    const updated = toggleChecklistItems(SAMPLE_CHECKLIST, new Set([1]), items);
    const updatedItems = parseChecklistItems(updated);
    expect(updatedItems[0].done).toBe(false);
  });

  it('should toggle multiple items at once', () => {
    const items = parseChecklistItems(SAMPLE_CHECKLIST);
    const updated = toggleChecklistItems(SAMPLE_CHECKLIST, new Set([1, 3, 4]), items);
    const updatedItems = parseChecklistItems(updated);
    expect(updatedItems[0].done).toBe(false); // was checked → unchecked
    expect(updatedItems[1].done).toBe(true); // unchanged
    expect(updatedItems[2].done).toBe(true); // was unchecked → checked
    expect(updatedItems[3].done).toBe(true); // was unchecked → checked
    expect(updatedItems[4].done).toBe(false); // unchanged
  });

  it('should not modify content when toggle set is empty', () => {
    const items = parseChecklistItems(SAMPLE_CHECKLIST);
    const updated = toggleChecklistItems(SAMPLE_CHECKLIST, new Set(), items);
    expect(updated).toBe(SAMPLE_CHECKLIST);
  });
});

describe('getChecklistProgress', () => {
  it('should calculate progress correctly', () => {
    const items = parseChecklistItems(SAMPLE_CHECKLIST);
    const progress = getChecklistProgress(items);
    expect(progress).toEqual({ done: 2, total: 5, percent: 40 });
  });

  it('should return 0% for all unchecked', () => {
    const allUnchecked = SAMPLE_CHECKLIST.replace(/\[x\]/g, '[ ]');
    const items = parseChecklistItems(allUnchecked);
    const progress = getChecklistProgress(items);
    expect(progress).toEqual({ done: 0, total: 5, percent: 0 });
  });

  it('should return 100% for all checked', () => {
    const allChecked = SAMPLE_CHECKLIST.replace(/\[ \]/g, '[x]');
    const items = parseChecklistItems(allChecked);
    const progress = getChecklistProgress(items);
    expect(progress).toEqual({ done: 5, total: 5, percent: 100 });
  });

  it('should handle empty items array', () => {
    const progress = getChecklistProgress([]);
    expect(progress).toEqual({ done: 0, total: 0, percent: 0 });
  });
});
